// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v5.29.3
// source: common.proto

/* eslint-disable */

export const protobufPackage = "common";

/** 通用时间戳消息 */
export interface Timestamp {
  /** 时间戳（ISO 8601 格式字符串） */
  value: string;
}

/** 通用分页请求 */
export interface PaginationRequest {
  /** 页码，从1开始 */
  page: number;
  /** 每页大小，默认20 */
  pageSize: number;
}

/** 通用分页响应 */
export interface PaginationResponse {
  /** 当前页码 */
  page: number;
  /** 每页大小 */
  pageSize: number;
  /** 总记录数 */
  total: string;
  /** 总页数 */
  totalPages: number;
}

/** 通用响应状态 */
export interface ResponseStatus {
  /** 状态码 */
  code: number;
  /** 状态消息 */
  message: string;
  /** 是否成功 */
  success: boolean;
}

/** 通用错误信息 */
export interface ErrorDetail {
  /** 错误码 */
  code: string;
  /** 错误消息 */
  message: string;
  /** 错误字段（用于表单验证错误） */
  field: string;
}
