// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v5.29.3
// source: common.proto

/* eslint-disable */

export const protobufPackage = "common";

/** 通用分页请求 */
export interface PaginationRequest {
  /** 页码，从1开始 */
  page: number;
  /** 每页大小，默认20 */
  pageSize: number;
}

/** 通用分页响应 */
export interface PaginationResponse {
  /** 当前页码 */
  page: number;
  /** 每页大小 */
  pageSize: number;
  /** 总记录数 */
  total: string;
  /** 总页数 */
  totalPages: number;
}

/** 通用响应状态 */
export interface ResponseStatus {
  /** 状态码 */
  code: number;
  /** 状态消息 */
  message: string;
  /** 是否成功 */
  success: boolean;
}

/** 通用空请求 */
export interface EmptyRequest {
}

/** 通用错误信息 */
export interface ErrorDetail {
  /** 错误码 */
  code: string;
  /** 错误消息 */
  message: string;
  /** 错误字段（用于表单验证错误） */
  field: string;
}

/** 枚举项 */
export interface EnumItem {
  /** 枚举值（支持字符串和数字） */
  valueType?:
    | { $case: "valueStr"; valueStr: string }
    | { $case: "value"; value: number }
    | undefined;
  /** 显示标签 */
  label: string;
  /** 是否禁用 */
  disabled?:
    | boolean
    | undefined;
  /** 扩展属性（JSON格式） */
  extra?: string | undefined;
}

/** 枚举项列表 */
export interface EnumItemList {
  /** 枚举项数组 */
  values: EnumItem[];
}

/** 枚举响应 */
export interface EnumResponse {
  /** 枚举项映射（每个枚举对应一个 EnumItem 数组） */
  enums: Map<string, EnumItemList>;
  /** 版本信息 */
  version?: string | undefined;
}

export interface EnumResponse_EnumsEntry {
  key: string;
  value?: EnumItemList | undefined;
}
