// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v5.29.3
// source: health.proto

/* eslint-disable */
import { Observable } from "rxjs";

export const protobufPackage = "grpc.health.v1";

/** 健康检查请求 */
export interface HealthCheckRequest {
  /** 要检查的服务名称。空字符串表示检查整个服务器的健康状态 */
  service: string;
}

/** 健康检查响应 */
export interface HealthCheckResponse {
  /** 服务状态 */
  status: HealthCheckResponse_ServingStatus;
}

export enum HealthCheckResponse_ServingStatus {
  UNKNOWN = "UNKNOWN",
  SERVING = "SERVING",
  NOT_SERVING = "NOT_SERVING",
  /** SERVICE_UNKNOWN - 用于未知的服务 */
  SERVICE_UNKNOWN = "SERVICE_UNKNOWN",
  UNRECOGNIZED = "UNRECOGNIZED",
}

/** 健康检查服务 */
export interface Health {
  /** 检查服务健康状态 */
  Check(request: HealthCheckRequest): Promise<HealthCheckResponse>;
  /** 监听服务健康状态变化 */
  Watch(request: HealthCheckRequest): Observable<HealthCheckResponse>;
}
