// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v5.29.3
// source: rbac.proto

/* eslint-disable */
import type { PaginationRequest, PaginationResponse, ResponseStatus } from "./common";

export const protobufPackage = "rbac";

/** 权限信息 */
export interface Permission {
  /** 权限ID */
  id: string;
  /** 权限名称 */
  name: string;
  /** 权限动作 */
  action: string;
  /** 权限资源 */
  resource: string;
  /** 权限描述 */
  description: string;
  /** 是否激活 */
  isActive: boolean;
  /** 创建时间 */
  createdAt: string;
  /** 更新时间 */
  updatedAt: string;
}

/** 角色信息 */
export interface Role {
  /** 角色ID */
  id: string;
  /** 角色名称 */
  name: string;
  /** 角色描述 */
  description: string;
  /** 是否激活 */
  isActive: boolean;
  /** 创建时间 */
  createdAt: string;
  /** 更新时间 */
  updatedAt: string;
  /** 权限列表 */
  permissions: Permission[];
}

/** 获取权限请求 */
export interface GetPermissionRequest {
  /** 权限ID */
  id: string;
}

/** 获取权限列表请求 */
export interface GetPermissionsRequest {
  /** 分页信息 */
  pagination?:
    | PaginationRequest
    | undefined;
  /** 搜索关键词（可选） */
  search?:
    | string
    | undefined;
  /** 是否激活过滤（可选） */
  isActive?:
    | boolean
    | undefined;
  /** 权限动作过滤（可选） */
  action?:
    | string
    | undefined;
  /** 权限资源过滤（可选） */
  resource?: string | undefined;
}

/** 权限列表响应 */
export interface GetPermissionsResponse {
  /** 权限列表 */
  permissions: Permission[];
  /** 分页信息 */
  pagination?: PaginationResponse | undefined;
}

/** 创建权限请求 */
export interface CreatePermissionRequest {
  /** 权限名称 */
  name: string;
  /** 权限动作 */
  action: string;
  /** 权限资源 */
  resource: string;
  /** 权限描述 */
  description: string;
}

/** 更新权限请求 */
export interface UpdatePermissionRequest {
  /** 权限ID */
  id: string;
  /** 权限名称（可选） */
  name?:
    | string
    | undefined;
  /** 权限动作（可选） */
  action?:
    | string
    | undefined;
  /** 权限资源（可选） */
  resource?:
    | string
    | undefined;
  /** 权限描述（可选） */
  description?:
    | string
    | undefined;
  /** 是否激活（可选） */
  isActive?: boolean | undefined;
}

/** 获取角色请求 */
export interface GetRoleRequest {
  /** 角色ID */
  id: string;
}

/** 获取角色列表请求 */
export interface GetRolesRequest {
  /** 分页信息 */
  pagination?:
    | PaginationRequest
    | undefined;
  /** 搜索关键词（可选） */
  search?:
    | string
    | undefined;
  /** 是否激活过滤（可选） */
  isActive?: boolean | undefined;
}

/** 角色列表响应 */
export interface GetRolesResponse {
  /** 角色列表 */
  roles: Role[];
  /** 分页信息 */
  pagination?: PaginationResponse | undefined;
}

/** 创建角色请求 */
export interface CreateRoleRequest {
  /** 角色名称 */
  name: string;
  /** 角色描述 */
  description: string;
  /** 权限ID列表 */
  permissionIds: string[];
}

/** 更新角色请求 */
export interface UpdateRoleRequest {
  /** 角色ID */
  id: string;
  /** 角色名称（可选） */
  name?:
    | string
    | undefined;
  /** 角色描述（可选） */
  description?:
    | string
    | undefined;
  /** 是否激活（可选） */
  isActive?:
    | boolean
    | undefined;
  /** 权限ID列表（可选） */
  permissionIds: string[];
}

/** 分配角色权限请求 */
export interface AssignRolePermissionsRequest {
  /** 角色ID */
  roleId: string;
  /** 权限ID列表 */
  permissionIds: string[];
}

/** 移除角色权限请求 */
export interface RemoveRolePermissionsRequest {
  /** 角色ID */
  roleId: string;
  /** 权限ID列表 */
  permissionIds: string[];
}

/** 检查权限请求 */
export interface CheckPermissionRequest {
  /** 用户手机号 */
  userPhone: string;
  /** 权限动作 */
  action: string;
  /** 权限资源 */
  resource: string;
}

/** 检查权限响应 */
export interface CheckPermissionResponse {
  /** 是否有权限 */
  hasPermission: boolean;
  /** 权限详情 */
  matchedPermissions: Permission[];
}

/** 权限服务定义 */
export interface PermissionService {
  /** 获取权限信息 */
  GetPermission(request: GetPermissionRequest): Promise<Permission>;
  /** 获取权限列表 */
  GetPermissions(request: GetPermissionsRequest): Promise<GetPermissionsResponse>;
  /** 创建权限 */
  CreatePermission(request: CreatePermissionRequest): Promise<Permission>;
  /** 更新权限 */
  UpdatePermission(request: UpdatePermissionRequest): Promise<Permission>;
  /** 删除权限 */
  DeletePermission(request: GetPermissionRequest): Promise<ResponseStatus>;
  /** 检查用户权限 */
  CheckPermission(request: CheckPermissionRequest): Promise<CheckPermissionResponse>;
}

/** 角色服务定义 */
export interface RoleService {
  /** 获取角色信息 */
  GetRole(request: GetRoleRequest): Promise<Role>;
  /** 获取角色列表 */
  GetRoles(request: GetRolesRequest): Promise<GetRolesResponse>;
  /** 创建角色 */
  CreateRole(request: CreateRoleRequest): Promise<Role>;
  /** 更新角色 */
  UpdateRole(request: UpdateRoleRequest): Promise<Role>;
  /** 删除角色 */
  DeleteRole(request: GetRoleRequest): Promise<ResponseStatus>;
  /** 分配角色权限 */
  AssignRolePermissions(request: AssignRolePermissionsRequest): Promise<ResponseStatus>;
  /** 移除角色权限 */
  RemoveRolePermissions(request: RemoveRolePermissionsRequest): Promise<ResponseStatus>;
}
