// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v5.29.3
// source: resource.proto

/* eslint-disable */
import type { EmptyRequest, EnumResponse, ResponseStatus } from "./common";

export const protobufPackage = "resource";

/** 基础资源类型（不包含children，用于列表和详情） */
export interface Resource {
  id: string;
  name: string;
  /** 使用基础类型代替枚举 */
  type: number;
  /** 可选字段使用optional */
  icon?:
    | string
    | undefined;
  /** 可选字段 */
  parentId?: string | undefined;
  sortOrder: number;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  /** 可选字段 */
  description?: string | undefined;
  level: number;
  metadata: Map<string, string>;
  path: string;
}

export interface Resource_MetadataEntry {
  key: string;
  value: string;
}

/** 树形资源类型（包含children，用于树形结构） */
export interface ResourceTree {
  id: string;
  name: string;
  /** 使用基础类型 */
  type: number;
  /** 可选字段 */
  icon?:
    | string
    | undefined;
  /** 可选字段 */
  parentId?: string | undefined;
  sortOrder: number;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  /** 可选字段 */
  description?: string | undefined;
  level: number;
  metadata: Map<string, string>;
  path: string;
  /** 树形结构包含children */
  children: ResourceTree[];
}

export interface ResourceTree_MetadataEntry {
  key: string;
  value: string;
}

export interface CreateResourceRequest {
  name: string;
  /** 使用基础类型 */
  type: number;
  /** 可选字段 */
  parentId?: string | undefined;
  path: string;
  /** 可选字段 */
  description?: string | undefined;
  metadata: Map<string, string>;
}

export interface CreateResourceRequest_MetadataEntry {
  key: string;
  value: string;
}

export interface UpdateResourceRequest {
  id: string;
  name: string;
  /** 使用基础类型 */
  type: number;
  /** 可选字段 */
  parentId?: string | undefined;
  path: string;
  /** 可选字段 */
  description?: string | undefined;
  metadata: Map<string, string>;
  isActive: boolean;
}

export interface UpdateResourceRequest_MetadataEntry {
  key: string;
  value: string;
}

export interface GetResourceRequest {
  id: string;
}

export interface GetResourcesRequest {
  /** 使用基础类型 */
  type?: number | undefined;
}

export interface GetResourceByPathRequest {
  path: string;
}

export interface MoveResourceRequest {
  id: string;
  parentId?: string | undefined;
}

export interface DuplicateResourceRequest {
  id: string;
  parentId?: string | undefined;
  newName?: string | undefined;
}

export interface BatchDeleteResourcesRequest {
  ids: string[];
}

export interface ResourceListResponse {
  data: Resource[];
}

export interface ResourceResponse {
  data?: Resource | undefined;
}

export interface ResourceTreeResponse {
  /** 树形响应使用ResourceTree类型 */
  data: ResourceTree[];
}

export interface ResourcePathResponse {
  /** 路径响应使用基础Resource类型 */
  data: Resource[];
}

export interface ResourceService {
  /** 获取资源枚举 */
  GetResourceEnums(request: EmptyRequest): Promise<EnumResponse>;
  /** 创建资源 */
  CreateResource(request: CreateResourceRequest): Promise<ResourceResponse>;
  /** 获取资源列表 */
  GetResources(request: GetResourcesRequest): Promise<ResourceListResponse>;
  /** 获取资源树 */
  GetResourceTree(request: GetResourcesRequest): Promise<ResourceTreeResponse>;
  /** 根据ID获取资源 */
  GetResource(request: GetResourceRequest): Promise<ResourceResponse>;
  /** 获取资源路径 */
  GetResourcePath(request: GetResourceRequest): Promise<ResourcePathResponse>;
  /** 获取资源子级树 */
  GetSubtree(request: GetResourceRequest): Promise<ResourceTreeResponse>;
  /** 更新资源 */
  UpdateResource(request: UpdateResourceRequest): Promise<ResourceResponse>;
  /** 移动资源 */
  MoveResource(request: MoveResourceRequest): Promise<ResourceResponse>;
  /** 复制资源 */
  DuplicateResource(request: DuplicateResourceRequest): Promise<ResourceResponse>;
  /** 删除资源 */
  DeleteResource(request: GetResourceRequest): Promise<ResponseStatus>;
  /** 批量删除资源 */
  BatchDeleteResources(request: BatchDeleteResourcesRequest): Promise<ResponseStatus>;
  /** 根据路径获取资源 */
  GetResourceByPath(request: GetResourceByPathRequest): Promise<ResourceResponse>;
  /** 验证树形结构 */
  ValidateTree(request: EmptyRequest): Promise<ResponseStatus>;
}
