// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v5.29.3
// source: role.proto

/* eslint-disable */
import type { PaginationRequest, ResponseStatus } from "./common";

export const protobufPackage = "role";

/** 角色信息 */
export interface Role {
  /** 角色ID */
  id: string;
  /** 角色名称 */
  name: string;
  /** 角色描述 */
  description?:
    | string
    | undefined;
  /** 是否激活 */
  isActive: boolean;
  /** 是否为超级管理员 */
  isSuperAdmin: boolean;
  /** 创建时间 */
  createdAt: string;
  /** 更新时间 */
  updatedAt: string;
  /** 角色拥有的资源ID列表 */
  resourceIds: string[];
}

/** 创建角色请求 */
export interface CreateRoleRequest {
  /** 角色名称 */
  name: string;
  /** 角色描述（可选） */
  description?:
    | string
    | undefined;
  /** 是否激活（可选，默认true） */
  isActive?:
    | boolean
    | undefined;
  /** 是否为超级管理员（可选，默认false） */
  isSuperAdmin?:
    | boolean
    | undefined;
  /** 角色拥有的资源ID列表 */
  resourceIds: string[];
}

/** 更新角色请求 */
export interface UpdateRoleRequest {
  /** 角色ID */
  id: string;
  /** 角色名称（可选） */
  name?:
    | string
    | undefined;
  /** 角色描述（可选） */
  description?:
    | string
    | undefined;
  /** 是否激活（可选） */
  isActive?:
    | boolean
    | undefined;
  /** 是否为超级管理员（可选） */
  isSuperAdmin?:
    | boolean
    | undefined;
  /** 角色拥有的资源ID列表 */
  resourceIds: string[];
}

/** 获取角色请求 */
export interface GetRoleRequest {
  /** 角色ID */
  id: string;
}

/** 获取角色列表请求 */
export interface GetRolesRequest {
  /** 搜索关键词（可选，按名称搜索） */
  search?:
    | string
    | undefined;
  /** 是否激活过滤（可选） */
  isActive?:
    | boolean
    | undefined;
  /** 是否超级管理员过滤（可选） */
  isSuperAdmin?:
    | boolean
    | undefined;
  /** 分页信息 */
  pagination?: PaginationRequest | undefined;
}

export interface GetRolesResponse {
  data: Role[];
}

/** 删除角色请求 */
export interface DeleteRoleRequest {
  /** 角色ID */
  id: string;
}

/** 分配权限给角色请求 */
export interface AssignPermissionsToRoleRequest {
  /** 角色ID */
  roleId: string;
  /** 资源ID列表 */
  resourceIds: string[];
}

/** 移除角色权限请求 */
export interface RemoveRolePermissionsRequest {
  /** 角色ID */
  roleId: string;
  /** 资源ID列表 */
  resourceIds: string[];
}

/** 角色服务定义 */
export interface RoleService {
  /** 获取角色信息 */
  GetRole(request: GetRoleRequest): Promise<Role>;
  /** 获取角色列表 */
  GetRoles(request: GetRolesRequest): Promise<GetRolesResponse>;
  /** 创建角色 */
  CreateRole(request: CreateRoleRequest): Promise<Role>;
  /** 更新角色 */
  UpdateRole(request: UpdateRoleRequest): Promise<Role>;
  /** 删除角色 */
  DeleteRole(request: DeleteRoleRequest): Promise<ResponseStatus>;
  /** 分配权限给角色 */
  AssignPermissionsToRole(request: AssignPermissionsToRoleRequest): Promise<ResponseStatus>;
  /** 移除角色权限 */
  RemoveRolePermissions(request: RemoveRolePermissionsRequest): Promise<ResponseStatus>;
}
