// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v5.29.3
// source: role.proto

/* eslint-disable */
import type { EmptyRequest, PaginationRequest, PaginationResponse, ResponseStatus } from "./common";
import type { Resource } from "./resource";

export const protobufPackage = "role";

/** 角色信息 */
export interface Role {
  /** 角色ID */
  id: string;
  /** 角色名称 */
  name: string;
  /** 角色描述 */
  description?:
    | string
    | undefined;
  /** 是否激活 */
  isActive: boolean;
  /** 是否为超级管理员 */
  isSuperAdmin: boolean;
  /** 创建时间 */
  createdAt: string;
  /** 更新时间 */
  updatedAt: string;
}

/** 角色权限树节点 */
export interface RolePermissionTreeNode {
  /** 资源信息 */
  resource?:
    | Resource
    | undefined;
  /** 是否已分配 */
  isAssigned: boolean;
  /** 是否部分分配 */
  isIndeterminate: boolean;
  /** 子节点 */
  children: RolePermissionTreeNode[];
}

/** 创建角色请求 */
export interface CreateRoleRequest {
  /** 角色名称 */
  name: string;
  /** 角色描述（可选） */
  description?:
    | string
    | undefined;
  /** 是否激活（可选，默认true） */
  isActive?:
    | boolean
    | undefined;
  /** 是否为超级管理员（可选，默认false） */
  isSuperAdmin?: boolean | undefined;
}

/** 更新角色请求 */
export interface UpdateRoleRequest {
  /** 角色ID */
  id: string;
  /** 角色名称（可选） */
  name?:
    | string
    | undefined;
  /** 角色描述（可选） */
  description?:
    | string
    | undefined;
  /** 是否激活（可选） */
  isActive?:
    | boolean
    | undefined;
  /** 是否为超级管理员（可选） */
  isSuperAdmin?: boolean | undefined;
}

/** 获取角色请求 */
export interface GetRoleRequest {
  /** 角色ID */
  id: string;
}

/** 获取角色列表请求 */
export interface GetRolesRequest {
  /** 搜索关键词（可选，按名称搜索） */
  search?:
    | string
    | undefined;
  /** 是否激活过滤（可选） */
  isActive?:
    | boolean
    | undefined;
  /** 是否超级管理员过滤（可选） */
  isSuperAdmin?:
    | boolean
    | undefined;
  /** 分页信息 */
  pagination?: PaginationRequest | undefined;
}

/** 角色列表响应 */
export interface GetRolesResponse {
  /** 角色列表 */
  roles: Role[];
  /** 分页信息 */
  pagination?: PaginationResponse | undefined;
}

/** 删除角色请求 */
export interface DeleteRoleRequest {
  /** 角色ID */
  id: string;
}

/** 分配权限给角色请求 */
export interface AssignPermissionsToRoleRequest {
  /** 角色ID */
  roleId: string;
  /** 资源ID列表 */
  resourceIds: string[];
}

/** 移除角色权限请求 */
export interface RemoveRolePermissionsRequest {
  /** 角色ID */
  roleId: string;
  /** 资源ID列表 */
  resourceIds: string[];
}

/** 获取角色权限请求 */
export interface GetRolePermissionsRequest {
  /** 角色ID */
  roleId: string;
  /** 是否包含子权限（可选，默认false） */
  includeChildren?: boolean | undefined;
}

/** 角色权限响应 */
export interface GetRolePermissionsResponse {
  /** 角色信息 */
  role?:
    | Role
    | undefined;
  /** 权限树 */
  permissionTree: RolePermissionTreeNode[];
  /** 权限资源列表 */
  permissions: Resource[];
}

/** 分配用户给角色请求 */
export interface AssignUsersToRoleRequest {
  /** 角色ID */
  roleId: string;
  /** 用户ID列表（手机号） */
  userIds: string[];
}

/** 移除角色用户请求 */
export interface RemoveRoleUsersRequest {
  /** 角色ID */
  roleId: string;
  /** 用户ID列表（手机号） */
  userIds: string[];
}

/** 获取角色用户请求 */
export interface GetRoleUsersRequest {
  /** 角色ID */
  roleId: string;
  /** 分页信息 */
  pagination?: PaginationRequest | undefined;
}

/** 角色用户响应 */
export interface GetRoleUsersResponse {
  /** 角色信息 */
  role?:
    | Role
    | undefined;
  /** 用户列表 */
  userIds: string[];
  /** 分页信息 */
  pagination?: PaginationResponse | undefined;
}

/** 检查用户角色请求 */
export interface CheckUserRoleRequest {
  /** 用户ID（手机号） */
  userId: string;
  /** 角色ID（可选，如果不指定则检查所有角色） */
  roleId?: string | undefined;
}

/** 检查用户角色响应 */
export interface CheckUserRoleResponse {
  /** 是否拥有指定角色 */
  hasRole: boolean;
  /** 用户拥有的角色列表 */
  userRoles: Role[];
}

/** 获取用户角色请求 */
export interface GetUserRolesRequest {
  /** 用户ID（手机号） */
  userId: string;
}

/** 获取用户角色响应 */
export interface GetUserRolesResponse {
  /** 用户ID */
  userId: string;
  /** 角色列表 */
  roles: Role[];
}

/** 检查角色权限请求 */
export interface CheckRolePermissionRequest {
  /** 角色ID */
  roleId: string;
  /** 权限码 */
  permissionCode: string;
}

/** 检查角色权限响应 */
export interface CheckRolePermissionResponse {
  /** 是否拥有权限 */
  hasPermission: boolean;
  /** 匹配的资源信息 */
  matchedResources: Resource[];
}

/** 角色统计信息 */
export interface RoleStatistics {
  /** 总角色数 */
  totalRoles: number;
  /** 按状态统计 */
  rolesByStatus: Map<string, number>;
  /** 平均权限数 */
  averagePermissionsPerRole: number;
  /** 总用户角色关联数 */
  totalUserRoleAssignments: number;
}

export interface RoleStatistics_RolesByStatusEntry {
  key: string;
  value: number;
}

/** 角色服务定义 */
export interface RoleService {
  /** 获取角色信息 */
  GetRole(request: GetRoleRequest): Promise<Role>;
  /** 获取角色列表 */
  GetRoles(request: GetRolesRequest): Promise<GetRolesResponse>;
  /** 创建角色 */
  CreateRole(request: CreateRoleRequest): Promise<Role>;
  /** 更新角色 */
  UpdateRole(request: UpdateRoleRequest): Promise<Role>;
  /** 删除角色 */
  DeleteRole(request: DeleteRoleRequest): Promise<ResponseStatus>;
  /** 分配权限给角色 */
  AssignPermissionsToRole(request: AssignPermissionsToRoleRequest): Promise<ResponseStatus>;
  /** 移除角色权限 */
  RemoveRolePermissions(request: RemoveRolePermissionsRequest): Promise<ResponseStatus>;
  /** 获取角色权限 */
  GetRolePermissions(request: GetRolePermissionsRequest): Promise<GetRolePermissionsResponse>;
  /** 分配用户给角色 */
  AssignUsersToRole(request: AssignUsersToRoleRequest): Promise<ResponseStatus>;
  /** 移除角色用户 */
  RemoveRoleUsers(request: RemoveRoleUsersRequest): Promise<ResponseStatus>;
  /** 获取角色用户 */
  GetRoleUsers(request: GetRoleUsersRequest): Promise<GetRoleUsersResponse>;
  /** 检查用户角色 */
  CheckUserRole(request: CheckUserRoleRequest): Promise<CheckUserRoleResponse>;
  /** 获取用户角色 */
  GetUserRoles(request: GetUserRolesRequest): Promise<GetUserRolesResponse>;
  /** 检查角色权限 */
  CheckRolePermission(request: CheckRolePermissionRequest): Promise<CheckRolePermissionResponse>;
  /** 获取角色统计信息 */
  GetRoleStatistics(request: EmptyRequest): Promise<RoleStatistics>;
}
