// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v5.29.3
// source: users.proto

/* eslint-disable */
import type { EnumResponse, PaginationRequest, PaginationResponse, ResponseStatus } from "./common";
import type { Resource, ResourceTree } from "./resource";

export const protobufPackage = "users";

/** 精简用户信息 */
export interface SimpleUser {
  /** 手机号（主键） */
  phone: string;
  /** 用户名 */
  username: string;
}

/** 用户信息 */
export interface User {
  /** 手机号（主键） */
  phone: string;
  /** 用户名 */
  username: string;
  /** 用户状态：1-待激活，2-激活，3-下线，4-锁定 */
  status: number;
  /** 状态描述 */
  statusDesc: string;
  /** 创建时间 */
  createdAt: string;
  /** 更新时间 */
  updatedAt: string;
  /** 用户角色列表（可选） */
  roleIds: string[];
  /** 用户角色名称列表（可选） */
  roleNames: string[];
}

/** 登录请求 */
export interface LoginRequest {
  /** 手机号 */
  phone: string;
  /** 密码 */
  password: string;
}

/** 权限树响应 */
export interface PermissionTree {
  /** 菜单树 */
  menuTree: ResourceTree[];
  /** 所有资源列表 */
  resources: Resource[];
}

/** 个人资料响应 */
export interface ProfileResponse {
  /** 精简用户信息 */
  user?:
    | SimpleUser
    | undefined;
  /** 权限树 */
  permissions?: PermissionTree | undefined;
}

/** 认证响应 */
export interface AuthResponse {
  /** 精简用户信息 */
  user?:
    | SimpleUser
    | undefined;
  /** JWT token */
  token: string;
  /** token过期时间 */
  expiresAt: string;
}

/** 获取用户请求 */
export interface GetUserRequest {
  /** 用户手机号 */
  phone: string;
}

/** 创建用户请求 */
export interface CreateUserRequest {
  /** 手机号 */
  phone: string;
  /** 用户名 */
  username: string;
  /** 密码 */
  password: string;
  /** 角色ID列表（可选） */
  roleIds: string[];
}

/** 更新用户请求 */
export interface UpdateUserRequest {
  /** 手机号 */
  phone: string;
  /** 用户名（可选） */
  username?:
    | string
    | undefined;
  /** 用户状态（可选）：1-待激活，2-激活，3-下线，4-锁定 */
  status?:
    | number
    | undefined;
  /** 角色ID列表（可选） */
  roleIds: string[];
}

/** 删除用户请求 */
export interface DeleteUserRequest {
  /** 手机号 */
  phone: string;
}

/** 用户状态变更请求 */
export interface UpdateUserStatusRequest {
  /** 手机号 */
  phone: string;
  /** 新状态：1-待激活，2-激活，3-下线，4-锁定 */
  status: number;
}

/** 创建用户表单请求 */
export interface CreateUserFormRequest {
  /** 手机号 */
  phone: string;
  /** 用户名 */
  username: string;
}

/** 用户列表请求 */
export interface GetUsersRequest {
  /** 分页信息 */
  pagination?:
    | PaginationRequest
    | undefined;
  /** 手机号 */
  phone?:
    | string
    | undefined;
  /** 用户名 */
  username?:
    | string
    | undefined;
  /** 角色ID */
  roleIds: string[];
  /** 状态列表（可选） */
  statusList: number[];
}

/** 用户列表响应 */
export interface GetUsersResponse {
  /** 用户列表 */
  list: User[];
  /** 分页信息 */
  pagination?: PaginationResponse | undefined;
}

/** 注册请求 */
export interface RegisterRequest {
  /** 手机号 */
  phone: string;
  /** 用户名 */
  username: string;
  /** 密码 */
  password: string;
  /** 验证码 */
  verificationCode: string;
}

/** 创建超级管理员请求 */
export interface CreateSuperAdminRequest {
  /** 手机号 */
  phone: string;
  /** 用户名 */
  username: string;
  /** 密码 */
  password: string;
  /** 超级管理员密钥 */
  adminKey: string;
}

/** 获取用户枚举请求 */
export interface GetUserEnumsRequest {
  /** 可选：指定要获取的枚举类型 */
  enumTypes: string[];
}

/** 获取用户枚举响应 */
export interface GetUserEnumsResponse {
  /** 枚举响应数据 */
  data?: EnumResponse | undefined;
}

/** 用户服务定义 */
export interface UserService {
  /** 获取用户枚举 */
  GetUserEnums(request: GetUserEnumsRequest): Promise<GetUserEnumsResponse>;
  /** 用户登录 */
  Login(request: LoginRequest): Promise<AuthResponse>;
  /** 获取当前用户信息 */
  GetProfile(request: GetUserRequest): Promise<ProfileResponse>;
  /** 获取用户信息 */
  GetUser(request: GetUserRequest): Promise<User>;
  /** 获取用户列表 */
  GetUsers(request: GetUsersRequest): Promise<GetUsersResponse>;
  /** 更新用户 */
  UpdateUser(request: UpdateUserRequest): Promise<User>;
  /** 删除用户 */
  DeleteUser(request: GetUserRequest): Promise<ResponseStatus>;
  /** 创建超级管理员 */
  CreateSuperAdmin(request: CreateSuperAdminRequest): Promise<AuthResponse>;
}
