// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v5.29.3
// source: users.proto

/* eslint-disable */
import type { PaginationRequest, PaginationResponse, ResponseStatus, Timestamp } from "./common";

export const protobufPackage = "users";

/** 用户信息 */
export interface User {
  /** 手机号（主键） */
  phone: string;
  /** 用户名 */
  username: string;
  /** 是否激活 */
  isActive: boolean;
  /** 创建时间 */
  createdAt?:
    | Timestamp
    | undefined;
  /** 更新时间 */
  updatedAt?:
    | Timestamp
    | undefined;
  /** 用户角色列表 */
  roleIds: string[];
}

/** 登录请求 */
export interface LoginRequest {
  /** 手机号 */
  phone: string;
  /** 密码 */
  password: string;
}

/** 认证响应 */
export interface AuthResponse {
  /** 用户信息 */
  user?:
    | User
    | undefined;
  /** JWT token */
  token: string;
  /** token过期时间 */
  expiresAt?: Timestamp | undefined;
}

/** 获取用户请求 */
export interface GetUserRequest {
  /** 用户手机号 */
  phone: string;
}

/** 创建用户请求 */
export interface CreateUserRequest {
  /** 手机号 */
  phone: string;
  /** 用户名 */
  username: string;
  /** 密码 */
  password: string;
  /** 角色ID列表 */
  roleIds: string[];
}

/** 更新用户请求 */
export interface UpdateUserRequest {
  /** 手机号 */
  phone: string;
  /** 用户名（可选） */
  username?:
    | string
    | undefined;
  /** 是否激活（可选） */
  isActive?:
    | boolean
    | undefined;
  /** 角色ID列表（可选） */
  roleIds: string[];
}

/** 用户列表请求 */
export interface GetUsersRequest {
  /** 分页信息 */
  pagination?:
    | PaginationRequest
    | undefined;
  /** 搜索关键词（可选） */
  search?:
    | string
    | undefined;
  /** 是否激活过滤（可选） */
  isActive?: boolean | undefined;
}

/** 用户列表响应 */
export interface GetUsersResponse {
  /** 用户列表 */
  users: User[];
  /** 分页信息 */
  pagination?: PaginationResponse | undefined;
}

/** 注册请求 */
export interface RegisterRequest {
  /** 手机号 */
  phone: string;
  /** 用户名 */
  username: string;
  /** 密码 */
  password: string;
  /** 验证码 */
  verificationCode: string;
}

/** 创建超级管理员请求 */
export interface CreateSuperAdminRequest {
  /** 手机号 */
  phone: string;
  /** 用户名 */
  username: string;
  /** 密码 */
  password: string;
  /** 超级管理员密钥 */
  adminKey: string;
}

/** 用户服务定义 */
export interface UserService {
  /** 用户登录 */
  Login(request: LoginRequest): Promise<AuthResponse>;
  /** 用户注册 */
  Register(request: RegisterRequest): Promise<AuthResponse>;
  /** 获取当前用户信息 */
  GetProfile(request: GetUserRequest): Promise<User>;
  /** 获取用户信息 */
  GetUser(request: GetUserRequest): Promise<User>;
  /** 获取用户列表 */
  GetUsers(request: GetUsersRequest): Promise<GetUsersResponse>;
  /** 创建用户 */
  CreateUser(request: CreateUserRequest): Promise<User>;
  /** 更新用户 */
  UpdateUser(request: UpdateUserRequest): Promise<User>;
  /** 删除用户 */
  DeleteUser(request: GetUserRequest): Promise<ResponseStatus>;
  /** 创建超级管理员 */
  CreateSuperAdmin(request: CreateSuperAdminRequest): Promise<AuthResponse>;
}
