global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus 自监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # NestJS 应用监控
  - job_name: 'nest-app'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['nest-app:3000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'nest-grpc-app'

  # Nginx 监控
  - job_name: 'nginx'
    metrics_path: '/nginx_status'
    scrape_interval: 30s
    static_configs:
      - targets: ['nginx:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'nginx-proxy'

  # PostgreSQL 监控（需要 postgres_exporter）
  - job_name: 'postgres'
    scrape_interval: 30s
    static_configs:
      - targets: ['postgres-exporter:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'postgres-db'

  # Redis 监控（需要 redis_exporter）
  - job_name: 'redis'
    scrape_interval: 30s
    static_configs:
      - targets: ['redis-exporter:9121']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'redis-cache'

  # Node.js 进程监控
  - job_name: 'node-exporter'
    scrape_interval: 30s
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'docker-host'

# 告警规则
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# 存储配置
storage:
  tsdb:
    retention.time: 15d
    retention.size: 1GB 